# Generated by Django 5.0 on 2024-10-27 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_country_book_published_countries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
